# .slather.yml

ci_service: travis_ci
coverage_service: coveralls
xcodeproj: Travis-Fastlane-Slather.xcodeproj
workspace: Travis-Fastlane-Slather.xcworkspace
scheme: Travis-Fastlane-Slather
source_directory: Travis-Fastlane-Slather/
ignore: 
  - ExamplePodCode/*
  - ProjectTestsGroup/*